# Generated by Django 4.1.3 on 2022-11-12 21:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=posts.models.PostPosterPath, verbose_name='Post Poster')),
                ('title', models.CharField(max_length=50, verbose_name='Title of Post')),
                ('desceibtion', models.CharField(max_length=100, verbose_name='Title of Post')),
                ('author', models.CharField(max_length=50, verbose_name='Author of Post')),
                ('tags', models.CharField(max_length=500, verbose_name='Title of Post')),
                ('articleText', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.maincategories')),
            ],
        ),
    ]
